/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.setfive.fbphonebook;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int fbconnect=0x7f020000;
        public static final int fblogin=0x7f020001;
        public static final int icon=0x7f020002;
        public static final int loader=0x7f020003;
    }
    public static final class id {
        public static final int LinearLayout01=0x7f050000;
        public static final int LinearLayout02=0x7f050005;
        public static final int LinearLayout03=0x7f050008;
        public static final int LinearLayout04=0x7f05000c;
        public static final int TableLayout01=0x7f050001;
        public static final int TableRow01=0x7f050004;
        public static final int TableRow02=0x7f050002;
        public static final int TableRow03=0x7f05000b;
        public static final int TextView01=0x7f050009;
        public static final int connect=0x7f050006;
        public static final int fbProgress=0x7f050007;
        public static final int launch=0x7f05000d;
        public static final int progress=0x7f05000e;
        public static final int status=0x7f050003;
        public static final int url=0x7f05000a;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int helptext=0x7f040001;
    }
}
