/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.comp194;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int cloudy=0x7f020000;
        public static final int fair=0x7f020001;
        public static final int icon=0x7f020002;
        public static final int showers=0x7f020003;
        public static final int snowshow=0x7f020004;
        public static final int sunny=0x7f020005;
        public static final int umbrella=0x7f020006;
    }
    public static final class id {
        public static final int LinearLayout01=0x7f050000;
        public static final int TextView01=0x7f050001;
        public static final int fetchWeather=0x7f050003;
        public static final int weatherImage=0x7f050004;
        public static final int zipcode=0x7f050002;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
    }
}
