<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/05/06 17:03:27

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'DebugPDO',
  'dsn' => 'mysql:dbname=assassins;host=localhost',
  'username' => 'assassins',
  'password' => 'assassins12',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
