<?php

/**
 * Base class that represents a row from the 'user' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Wed May  6 19:29:42 2009
 *
 * @package    lib.model.om
 */
abstract class BaseUser extends BaseObject  implements Persistent {


  const PEER = 'UserPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        UserPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        string
	 */
	protected $id;

	/**
	 * The value for the password field.
	 * @var        string
	 */
	protected $password;

	/**
	 * The value for the kills field.
	 * @var        int
	 */
	protected $kills;

	/**
	 * The value for the deaths field.
	 * @var        int
	 */
	protected $deaths;

	/**
	 * The value for the games_played field.
	 * @var        int
	 */
	protected $games_played;

	/**
	 * The value for the wins field.
	 * @var        int
	 */
	protected $wins;

	/**
	 * The value for the losses field.
	 * @var        int
	 */
	protected $losses;

	/**
	 * The value for the current_game_id field.
	 * @var        int
	 */
	protected $current_game_id;

	/**
	 * The value for the latitude field.
	 * @var        string
	 */
	protected $latitude;

	/**
	 * The value for the longitude field.
	 * @var        string
	 */
	protected $longitude;

	/**
	 * @var        Game
	 */
	protected $aGame;

	/**
	 * @var        array Target[] Collection to store aggregation of Target objects.
	 */
	protected $collTargetsRelatedByFromUserId;

	/**
	 * @var        Criteria The criteria used to select the current contents of collTargetsRelatedByFromUserId.
	 */
	private $lastTargetRelatedByFromUserIdCriteria = null;

	/**
	 * @var        array Target[] Collection to store aggregation of Target objects.
	 */
	protected $collTargetsRelatedByToUserId;

	/**
	 * @var        Criteria The criteria used to select the current contents of collTargetsRelatedByToUserId.
	 */
	private $lastTargetRelatedByToUserIdCriteria = null;

	/**
	 * @var        array GameMember[] Collection to store aggregation of GameMember objects.
	 */
	protected $collGameMembers;

	/**
	 * @var        Criteria The criteria used to select the current contents of collGameMembers.
	 */
	private $lastGameMemberCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseUser object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     string
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [password] column value.
	 * 
	 * @return     string
	 */
	public function getPassword()
	{
		return $this->password;
	}

	/**
	 * Get the [kills] column value.
	 * 
	 * @return     int
	 */
	public function getKills()
	{
		return $this->kills;
	}

	/**
	 * Get the [deaths] column value.
	 * 
	 * @return     int
	 */
	public function getDeaths()
	{
		return $this->deaths;
	}

	/**
	 * Get the [games_played] column value.
	 * 
	 * @return     int
	 */
	public function getGamesPlayed()
	{
		return $this->games_played;
	}

	/**
	 * Get the [wins] column value.
	 * 
	 * @return     int
	 */
	public function getWins()
	{
		return $this->wins;
	}

	/**
	 * Get the [losses] column value.
	 * 
	 * @return     int
	 */
	public function getLosses()
	{
		return $this->losses;
	}

	/**
	 * Get the [current_game_id] column value.
	 * 
	 * @return     int
	 */
	public function getCurrentGameId()
	{
		return $this->current_game_id;
	}

	/**
	 * Get the [latitude] column value.
	 * 
	 * @return     string
	 */
	public function getLatitude()
	{
		return $this->latitude;
	}

	/**
	 * Get the [longitude] column value.
	 * 
	 * @return     string
	 */
	public function getLongitude()
	{
		return $this->longitude;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      string $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = UserPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [password] column.
	 * 
	 * @param      string $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setPassword($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->password !== $v) {
			$this->password = $v;
			$this->modifiedColumns[] = UserPeer::PASSWORD;
		}

		return $this;
	} // setPassword()

	/**
	 * Set the value of [kills] column.
	 * 
	 * @param      int $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setKills($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->kills !== $v) {
			$this->kills = $v;
			$this->modifiedColumns[] = UserPeer::KILLS;
		}

		return $this;
	} // setKills()

	/**
	 * Set the value of [deaths] column.
	 * 
	 * @param      int $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setDeaths($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->deaths !== $v) {
			$this->deaths = $v;
			$this->modifiedColumns[] = UserPeer::DEATHS;
		}

		return $this;
	} // setDeaths()

	/**
	 * Set the value of [games_played] column.
	 * 
	 * @param      int $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setGamesPlayed($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->games_played !== $v) {
			$this->games_played = $v;
			$this->modifiedColumns[] = UserPeer::GAMES_PLAYED;
		}

		return $this;
	} // setGamesPlayed()

	/**
	 * Set the value of [wins] column.
	 * 
	 * @param      int $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setWins($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->wins !== $v) {
			$this->wins = $v;
			$this->modifiedColumns[] = UserPeer::WINS;
		}

		return $this;
	} // setWins()

	/**
	 * Set the value of [losses] column.
	 * 
	 * @param      int $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setLosses($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->losses !== $v) {
			$this->losses = $v;
			$this->modifiedColumns[] = UserPeer::LOSSES;
		}

		return $this;
	} // setLosses()

	/**
	 * Set the value of [current_game_id] column.
	 * 
	 * @param      int $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setCurrentGameId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->current_game_id !== $v) {
			$this->current_game_id = $v;
			$this->modifiedColumns[] = UserPeer::CURRENT_GAME_ID;
		}

		if ($this->aGame !== null && $this->aGame->getId() !== $v) {
			$this->aGame = null;
		}

		return $this;
	} // setCurrentGameId()

	/**
	 * Set the value of [latitude] column.
	 * 
	 * @param      string $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setLatitude($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->latitude !== $v) {
			$this->latitude = $v;
			$this->modifiedColumns[] = UserPeer::LATITUDE;
		}

		return $this;
	} // setLatitude()

	/**
	 * Set the value of [longitude] column.
	 * 
	 * @param      string $v new value
	 * @return     User The current object (for fluent API support)
	 */
	public function setLongitude($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->longitude !== $v) {
			$this->longitude = $v;
			$this->modifiedColumns[] = UserPeer::LONGITUDE;
		}

		return $this;
	} // setLongitude()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (string) $row[$startcol + 0] : null;
			$this->password = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->kills = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->deaths = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->games_played = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->wins = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->losses = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->current_game_id = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->latitude = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->longitude = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 10; // 10 = UserPeer::NUM_COLUMNS - UserPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating User object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aGame !== null && $this->current_game_id !== $this->aGame->getId()) {
			$this->aGame = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UserPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = UserPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aGame = null;
			$this->collTargetsRelatedByFromUserId = null;
			$this->lastTargetRelatedByFromUserIdCriteria = null;

			$this->collTargetsRelatedByToUserId = null;
			$this->lastTargetRelatedByToUserIdCriteria = null;

			$this->collGameMembers = null;
			$this->lastGameMemberCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseUser:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UserPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			UserPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseUser:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseUser:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UserPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseUser:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			UserPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aGame !== null) {
				if ($this->aGame->isModified() || $this->aGame->isNew()) {
					$affectedRows += $this->aGame->save($con);
				}
				$this->setGame($this->aGame);
			}


			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = UserPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setNew(false);
				} else {
					$affectedRows += UserPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collTargetsRelatedByFromUserId !== null) {
				foreach ($this->collTargetsRelatedByFromUserId as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collTargetsRelatedByToUserId !== null) {
				foreach ($this->collTargetsRelatedByToUserId as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collGameMembers !== null) {
				foreach ($this->collGameMembers as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aGame !== null) {
				if (!$this->aGame->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aGame->getValidationFailures());
				}
			}


			if (($retval = UserPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collTargetsRelatedByFromUserId !== null) {
					foreach ($this->collTargetsRelatedByFromUserId as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collTargetsRelatedByToUserId !== null) {
					foreach ($this->collTargetsRelatedByToUserId as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collGameMembers !== null) {
					foreach ($this->collGameMembers as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = UserPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getPassword();
				break;
			case 2:
				return $this->getKills();
				break;
			case 3:
				return $this->getDeaths();
				break;
			case 4:
				return $this->getGamesPlayed();
				break;
			case 5:
				return $this->getWins();
				break;
			case 6:
				return $this->getLosses();
				break;
			case 7:
				return $this->getCurrentGameId();
				break;
			case 8:
				return $this->getLatitude();
				break;
			case 9:
				return $this->getLongitude();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = UserPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getPassword(),
			$keys[2] => $this->getKills(),
			$keys[3] => $this->getDeaths(),
			$keys[4] => $this->getGamesPlayed(),
			$keys[5] => $this->getWins(),
			$keys[6] => $this->getLosses(),
			$keys[7] => $this->getCurrentGameId(),
			$keys[8] => $this->getLatitude(),
			$keys[9] => $this->getLongitude(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = UserPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setPassword($value);
				break;
			case 2:
				$this->setKills($value);
				break;
			case 3:
				$this->setDeaths($value);
				break;
			case 4:
				$this->setGamesPlayed($value);
				break;
			case 5:
				$this->setWins($value);
				break;
			case 6:
				$this->setLosses($value);
				break;
			case 7:
				$this->setCurrentGameId($value);
				break;
			case 8:
				$this->setLatitude($value);
				break;
			case 9:
				$this->setLongitude($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = UserPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setPassword($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setKills($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setDeaths($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setGamesPlayed($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setWins($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setLosses($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setCurrentGameId($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setLatitude($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setLongitude($arr[$keys[9]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(UserPeer::DATABASE_NAME);

		if ($this->isColumnModified(UserPeer::ID)) $criteria->add(UserPeer::ID, $this->id);
		if ($this->isColumnModified(UserPeer::PASSWORD)) $criteria->add(UserPeer::PASSWORD, $this->password);
		if ($this->isColumnModified(UserPeer::KILLS)) $criteria->add(UserPeer::KILLS, $this->kills);
		if ($this->isColumnModified(UserPeer::DEATHS)) $criteria->add(UserPeer::DEATHS, $this->deaths);
		if ($this->isColumnModified(UserPeer::GAMES_PLAYED)) $criteria->add(UserPeer::GAMES_PLAYED, $this->games_played);
		if ($this->isColumnModified(UserPeer::WINS)) $criteria->add(UserPeer::WINS, $this->wins);
		if ($this->isColumnModified(UserPeer::LOSSES)) $criteria->add(UserPeer::LOSSES, $this->losses);
		if ($this->isColumnModified(UserPeer::CURRENT_GAME_ID)) $criteria->add(UserPeer::CURRENT_GAME_ID, $this->current_game_id);
		if ($this->isColumnModified(UserPeer::LATITUDE)) $criteria->add(UserPeer::LATITUDE, $this->latitude);
		if ($this->isColumnModified(UserPeer::LONGITUDE)) $criteria->add(UserPeer::LONGITUDE, $this->longitude);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(UserPeer::DATABASE_NAME);

		$criteria->add(UserPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     string
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      string $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of User (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setId($this->id);

		$copyObj->setPassword($this->password);

		$copyObj->setKills($this->kills);

		$copyObj->setDeaths($this->deaths);

		$copyObj->setGamesPlayed($this->games_played);

		$copyObj->setWins($this->wins);

		$copyObj->setLosses($this->losses);

		$copyObj->setCurrentGameId($this->current_game_id);

		$copyObj->setLatitude($this->latitude);

		$copyObj->setLongitude($this->longitude);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getTargetsRelatedByFromUserId() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addTargetRelatedByFromUserId($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getTargetsRelatedByToUserId() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addTargetRelatedByToUserId($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getGameMembers() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addGameMember($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     User Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     UserPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new UserPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Game object.
	 *
	 * @param      Game $v
	 * @return     User The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setGame(Game $v = null)
	{
		if ($v === null) {
			$this->setCurrentGameId(NULL);
		} else {
			$this->setCurrentGameId($v->getId());
		}

		$this->aGame = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Game object, it will not be re-added.
		if ($v !== null) {
			$v->addUser($this);
		}

		return $this;
	}


	/**
	 * Get the associated Game object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Game The associated Game object.
	 * @throws     PropelException
	 */
	public function getGame(PropelPDO $con = null)
	{
		if ($this->aGame === null && ($this->current_game_id !== null)) {
			$c = new Criteria(GamePeer::DATABASE_NAME);
			$c->add(GamePeer::ID, $this->current_game_id);
			$this->aGame = GamePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aGame->addUsers($this);
			 */
		}
		return $this->aGame;
	}

	/**
	 * Clears out the collTargetsRelatedByFromUserId collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addTargetsRelatedByFromUserId()
	 */
	public function clearTargetsRelatedByFromUserId()
	{
		$this->collTargetsRelatedByFromUserId = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collTargetsRelatedByFromUserId collection (array).
	 *
	 * By default this just sets the collTargetsRelatedByFromUserId collection to an empty array (like clearcollTargetsRelatedByFromUserId());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initTargetsRelatedByFromUserId()
	{
		$this->collTargetsRelatedByFromUserId = array();
	}

	/**
	 * Gets an array of Target objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this User has previously been saved, it will retrieve
	 * related TargetsRelatedByFromUserId from storage. If this User is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Target[]
	 * @throws     PropelException
	 */
	public function getTargetsRelatedByFromUserId($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTargetsRelatedByFromUserId === null) {
			if ($this->isNew()) {
			   $this->collTargetsRelatedByFromUserId = array();
			} else {

				$criteria->add(TargetPeer::FROM_USER_ID, $this->id);

				TargetPeer::addSelectColumns($criteria);
				$this->collTargetsRelatedByFromUserId = TargetPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(TargetPeer::FROM_USER_ID, $this->id);

				TargetPeer::addSelectColumns($criteria);
				if (!isset($this->lastTargetRelatedByFromUserIdCriteria) || !$this->lastTargetRelatedByFromUserIdCriteria->equals($criteria)) {
					$this->collTargetsRelatedByFromUserId = TargetPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastTargetRelatedByFromUserIdCriteria = $criteria;
		return $this->collTargetsRelatedByFromUserId;
	}

	/**
	 * Returns the number of related Target objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Target objects.
	 * @throws     PropelException
	 */
	public function countTargetsRelatedByFromUserId(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collTargetsRelatedByFromUserId === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(TargetPeer::FROM_USER_ID, $this->id);

				$count = TargetPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(TargetPeer::FROM_USER_ID, $this->id);

				if (!isset($this->lastTargetRelatedByFromUserIdCriteria) || !$this->lastTargetRelatedByFromUserIdCriteria->equals($criteria)) {
					$count = TargetPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collTargetsRelatedByFromUserId);
				}
			} else {
				$count = count($this->collTargetsRelatedByFromUserId);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Target object to this object
	 * through the Target foreign key attribute.
	 *
	 * @param      Target $l Target
	 * @return     void
	 * @throws     PropelException
	 */
	public function addTargetRelatedByFromUserId(Target $l)
	{
		if ($this->collTargetsRelatedByFromUserId === null) {
			$this->initTargetsRelatedByFromUserId();
		}
		if (!in_array($l, $this->collTargetsRelatedByFromUserId, true)) { // only add it if the **same** object is not already associated
			array_push($this->collTargetsRelatedByFromUserId, $l);
			$l->setFromUser($this);
		}
	}

	/**
	 * Clears out the collTargetsRelatedByToUserId collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addTargetsRelatedByToUserId()
	 */
	public function clearTargetsRelatedByToUserId()
	{
		$this->collTargetsRelatedByToUserId = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collTargetsRelatedByToUserId collection (array).
	 *
	 * By default this just sets the collTargetsRelatedByToUserId collection to an empty array (like clearcollTargetsRelatedByToUserId());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initTargetsRelatedByToUserId()
	{
		$this->collTargetsRelatedByToUserId = array();
	}

	/**
	 * Gets an array of Target objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this User has previously been saved, it will retrieve
	 * related TargetsRelatedByToUserId from storage. If this User is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Target[]
	 * @throws     PropelException
	 */
	public function getTargetsRelatedByToUserId($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTargetsRelatedByToUserId === null) {
			if ($this->isNew()) {
			   $this->collTargetsRelatedByToUserId = array();
			} else {

				$criteria->add(TargetPeer::TO_USER_ID, $this->id);

				TargetPeer::addSelectColumns($criteria);
				$this->collTargetsRelatedByToUserId = TargetPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(TargetPeer::TO_USER_ID, $this->id);

				TargetPeer::addSelectColumns($criteria);
				if (!isset($this->lastTargetRelatedByToUserIdCriteria) || !$this->lastTargetRelatedByToUserIdCriteria->equals($criteria)) {
					$this->collTargetsRelatedByToUserId = TargetPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastTargetRelatedByToUserIdCriteria = $criteria;
		return $this->collTargetsRelatedByToUserId;
	}

	/**
	 * Returns the number of related Target objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Target objects.
	 * @throws     PropelException
	 */
	public function countTargetsRelatedByToUserId(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collTargetsRelatedByToUserId === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(TargetPeer::TO_USER_ID, $this->id);

				$count = TargetPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(TargetPeer::TO_USER_ID, $this->id);

				if (!isset($this->lastTargetRelatedByToUserIdCriteria) || !$this->lastTargetRelatedByToUserIdCriteria->equals($criteria)) {
					$count = TargetPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collTargetsRelatedByToUserId);
				}
			} else {
				$count = count($this->collTargetsRelatedByToUserId);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Target object to this object
	 * through the Target foreign key attribute.
	 *
	 * @param      Target $l Target
	 * @return     void
	 * @throws     PropelException
	 */
	public function addTargetRelatedByToUserId(Target $l)
	{
		if ($this->collTargetsRelatedByToUserId === null) {
			$this->initTargetsRelatedByToUserId();
		}
		if (!in_array($l, $this->collTargetsRelatedByToUserId, true)) { // only add it if the **same** object is not already associated
			array_push($this->collTargetsRelatedByToUserId, $l);
			$l->setToUser($this);
		}
	}

	/**
	 * Clears out the collGameMembers collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addGameMembers()
	 */
	public function clearGameMembers()
	{
		$this->collGameMembers = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collGameMembers collection (array).
	 *
	 * By default this just sets the collGameMembers collection to an empty array (like clearcollGameMembers());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initGameMembers()
	{
		$this->collGameMembers = array();
	}

	/**
	 * Gets an array of GameMember objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this User has previously been saved, it will retrieve
	 * related GameMembers from storage. If this User is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array GameMember[]
	 * @throws     PropelException
	 */
	public function getGameMembers($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collGameMembers === null) {
			if ($this->isNew()) {
			   $this->collGameMembers = array();
			} else {

				$criteria->add(GameMemberPeer::USER_ID, $this->id);

				GameMemberPeer::addSelectColumns($criteria);
				$this->collGameMembers = GameMemberPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(GameMemberPeer::USER_ID, $this->id);

				GameMemberPeer::addSelectColumns($criteria);
				if (!isset($this->lastGameMemberCriteria) || !$this->lastGameMemberCriteria->equals($criteria)) {
					$this->collGameMembers = GameMemberPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastGameMemberCriteria = $criteria;
		return $this->collGameMembers;
	}

	/**
	 * Returns the number of related GameMember objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related GameMember objects.
	 * @throws     PropelException
	 */
	public function countGameMembers(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collGameMembers === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(GameMemberPeer::USER_ID, $this->id);

				$count = GameMemberPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(GameMemberPeer::USER_ID, $this->id);

				if (!isset($this->lastGameMemberCriteria) || !$this->lastGameMemberCriteria->equals($criteria)) {
					$count = GameMemberPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collGameMembers);
				}
			} else {
				$count = count($this->collGameMembers);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a GameMember object to this object
	 * through the GameMember foreign key attribute.
	 *
	 * @param      GameMember $l GameMember
	 * @return     void
	 * @throws     PropelException
	 */
	public function addGameMember(GameMember $l)
	{
		if ($this->collGameMembers === null) {
			$this->initGameMembers();
		}
		if (!in_array($l, $this->collGameMembers, true)) { // only add it if the **same** object is not already associated
			array_push($this->collGameMembers, $l);
			$l->setUser($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this User is new, it will return
	 * an empty collection; or if this User has previously
	 * been saved, it will retrieve related GameMembers from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in User.
	 */
	public function getGameMembersJoinGame($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(UserPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collGameMembers === null) {
			if ($this->isNew()) {
				$this->collGameMembers = array();
			} else {

				$criteria->add(GameMemberPeer::USER_ID, $this->id);

				$this->collGameMembers = GameMemberPeer::doSelectJoinGame($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(GameMemberPeer::USER_ID, $this->id);

			if (!isset($this->lastGameMemberCriteria) || !$this->lastGameMemberCriteria->equals($criteria)) {
				$this->collGameMembers = GameMemberPeer::doSelectJoinGame($criteria, $con, $join_behavior);
			}
		}
		$this->lastGameMemberCriteria = $criteria;

		return $this->collGameMembers;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collTargetsRelatedByFromUserId) {
				foreach ((array) $this->collTargetsRelatedByFromUserId as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collTargetsRelatedByToUserId) {
				foreach ((array) $this->collTargetsRelatedByToUserId as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collGameMembers) {
				foreach ((array) $this->collGameMembers as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collTargetsRelatedByFromUserId = null;
		$this->collTargetsRelatedByToUserId = null;
		$this->collGameMembers = null;
			$this->aGame = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseUser:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseUser::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseUser
