<?php


/**
 * This class adds structure of 'user' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Wed May  6 19:29:42 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class UserMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.UserMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(UserPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(UserPeer::TABLE_NAME);
		$tMap->setPhpName('User');
		$tMap->setClassname('User');

		$tMap->setUseIdGenerator(false);

		$tMap->addPrimaryKey('ID', 'Id', 'VARCHAR', true, 32);

		$tMap->addColumn('PASSWORD', 'Password', 'VARCHAR', false, 36);

		$tMap->addColumn('KILLS', 'Kills', 'INTEGER', false, null);

		$tMap->addColumn('DEATHS', 'Deaths', 'INTEGER', false, null);

		$tMap->addColumn('GAMES_PLAYED', 'GamesPlayed', 'INTEGER', false, null);

		$tMap->addColumn('WINS', 'Wins', 'INTEGER', false, null);

		$tMap->addColumn('LOSSES', 'Losses', 'INTEGER', false, null);

		$tMap->addForeignKey('CURRENT_GAME_ID', 'CurrentGameId', 'INTEGER', 'game', 'ID', false, null);

		$tMap->addColumn('LATITUDE', 'Latitude', 'VARCHAR', false, 45);

		$tMap->addColumn('LONGITUDE', 'Longitude', 'VARCHAR', false, 45);

	} // doBuild()

} // UserMapBuilder
