/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.setfive.assassins;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int assassin=0x7f020000;
        public static final int dot=0x7f020001;
        public static final int icon=0x7f020002;
        public static final int ninja=0x7f020003;
        public static final int splinter_cell_chaos_theory=0x7f020004;
    }
    public static final class id {
        public static final int ImageView01=0x7f050010;
        public static final int LinearLayout01=0x7f050001;
        public static final int LinearLayout02=0x7f050005;
        public static final int LinearLayout03=0x7f050003;
        public static final int TextView01=0x7f050000;
        public static final int TextView02=0x7f050014;
        public static final int createButton=0x7f05000c;
        public static final int createGameButton=0x7f050007;
        public static final int createGameIsPrivate=0x7f050004;
        public static final int createGameText=0x7f050002;
        public static final int createLoading=0x7f050006;
        public static final int doSignUp=0x7f050019;
        public static final int emailAddress=0x7f050015;
        public static final int homeJoinLayout=0x7f050008;
        public static final int homeLoading=0x7f050009;
        public static final int homeMessages=0x7f05000d;
        public static final int joinButton=0x7f05000b;
        public static final int joinGameId=0x7f05000a;
        public static final int killBtn=0x7f05000e;
        public static final int mapview=0x7f05000f;
        public static final int password=0x7f050016;
        public static final int play=0x7f05001a;
        public static final int serverMsg=0x7f05001b;
        public static final int showLogin=0x7f050011;
        public static final int showSignUp=0x7f050012;
        public static final int signUpLoading=0x7f050018;
        public static final int signupBanner=0x7f050013;
        public static final int tosCheck=0x7f050017;
    }
    public static final class layout {
        public static final int creategame=0x7f030000;
        public static final int homescreen=0x7f030001;
        public static final int main=0x7f030002;
        public static final int signup=0x7f030003;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
    }
}
